also do 1Password check on macOS

diff --git a/.chezmoiscripts/run_check-1password.sh.tmpl b/.chezmoiscripts/run_check-1password.sh.tmpl
--- a/.chezmoiscripts/run_check-1password.sh.tmpl
+++ b/.chezmoiscripts/run_check-1password.sh.tmpl
@@ -1,5 +1,15 @@
 #!/usr/bin/env zsh
 
+{{- if eq .chezmoi.os "darwin" }}
+ONEPWD_EXE="/Applications/1Password.app/Contents/MacOS/1Password"
+if ! [[ -x "$ONEPWD_EXE" ]]
+then
+  echo
+  echo "*** WARNING no executable found at $ONEPWD_EXE"
+  echo "*** Without 1Password running, some ssh key management will fail."
+  echo
+fi
+{{- else}}
 ONEPWD_EXE="/opt/1Password/1password"
 if ! [[ -x "$ONEPWD_EXE" ]]
 then
@@ -9,3 +19,4 @@ then
   echo "*** Also, without 1Password running, some ssh key management will fail."
   echo
 fi
+{{- end }}
